# Configuración del Proyecto STC-APP4G
CODIGO_PROYECTO = "STC-APP4G"
CARPETA_CONTRATOS = "I. Contratos Base - STC-APP4G/"
CARPETA_ANEXOS = "II. Contratos Anexos - STC-APP4G/"
CARPETA_ENTREGABLES = "ENTREGABLES - STC-APP4G/"
